import 'package:flutter/material.dart';
import 'package:preco_certo/app/core/config/message_constants.dart';
import 'package:preco_certo/l10n/app_localizations.dart';

mixin MessageTranslator<T extends StatefulWidget> on State<T> {
  String translateMessage(BuildContext context, String code) {
    final l10n = AppLocalizations.of(context)!;

    switch (code) {
      case MessageConstants.loginEyebrow:
        return l10n.loginEyebrow;
      case MessageConstants.loginTitle:
        return l10n.loginTitle;
      case MessageConstants.loginSubtitle:
        return l10n.loginSubtitle;
      case MessageConstants.loginEmailLabel:
        return l10n.loginEmailLabel;
      case MessageConstants.loginEmailHint:
        return l10n.loginEmailHint;
      case MessageConstants.loginPasswordLabel:
        return l10n.loginPasswordLabel;
      case MessageConstants.loginPasswordHint:
        return l10n.loginPasswordHint;
      case MessageConstants.loginShowPassword:
        return l10n.loginShowPassword;
      case MessageConstants.loginHidePassword:
        return l10n.loginHidePassword;
      case MessageConstants.loginUnlockButton:
        return l10n.loginUnlockButton;
      case MessageConstants.loginNoAccount:
        return l10n.loginNoAccount;
      case MessageConstants.loginCreateAccount:
        return l10n.loginCreateAccount;
      case MessageConstants.registerBack:
        return l10n.registerBack;
      case MessageConstants.registerEyebrow:
        return l10n.registerEyebrow;
      case MessageConstants.registerTitle:
        return l10n.registerTitle;
      case MessageConstants.registerSubtitle:
        return l10n.registerSubtitle;
      case MessageConstants.registerNameLabel:
        return l10n.registerNameLabel;
      case MessageConstants.registerNameHint:
        return l10n.registerNameHint;
      case MessageConstants.registerNameRequired:
        return l10n.registerNameRequired;
      case MessageConstants.registerEmailLabel:
        return l10n.registerEmailLabel;
      case MessageConstants.registerEmailHint:
        return l10n.registerEmailHint;
      case MessageConstants.registerEmailRequired:
        return l10n.registerEmailRequired;
      case MessageConstants.registerEmailInvalid:
        return l10n.registerEmailInvalid;
      case MessageConstants.registerPasswordLabel:
        return l10n.registerPasswordLabel;
      case MessageConstants.registerPasswordHint:
        return l10n.registerPasswordHint;
      case MessageConstants.registerPasswordRequired:
        return l10n.registerPasswordRequired;
      case MessageConstants.registerPasswordInvalid:
        return l10n.registerPasswordInvalid;
      case MessageConstants.registerSubmit:
        return l10n.registerSubmit;
      case MessageConstants.offersEyebrow:
        return l10n.offersEyebrow;
      case MessageConstants.offersTitle:
        return l10n.offersTitle;
      case MessageConstants.offersLocationUnset:
        return l10n.offersLocationUnset;
      case MessageConstants.offersLocationHint:
        return l10n.offersLocationHint;
      case MessageConstants.offersSearchHint:
        return l10n.offersSearchHint;
      case MessageConstants.offersListTitle:
        return l10n.offersListTitle;
      case MessageConstants.offersListSubtitle:
        return l10n.offersListSubtitle;
      case MessageConstants.offersLocationTitle:
        return l10n.offersLocationTitle;
      case MessageConstants.offersLocationSubtitle:
        return l10n.offersLocationSubtitle;
      case MessageConstants.offersUseDeviceLocation:
        return l10n.offersUseDeviceLocation;
      case MessageConstants.offersUseDeviceLocationHint:
        return l10n.offersUseDeviceLocationHint;
      case MessageConstants.offersUseAddress:
        return l10n.offersUseAddress;
      case MessageConstants.offersUseAddressHint:
        return l10n.offersUseAddressHint;
      case MessageConstants.offersAddressLabel:
        return l10n.offersAddressLabel;
      case MessageConstants.offersAddressHint:
        return l10n.offersAddressHint;
      case MessageConstants.offersSearchAddress:
        return l10n.offersSearchAddress;
      case MessageConstants.offersAddressResults:
        return l10n.offersAddressResults;
      case MessageConstants.offersRadiusLabel:
        return l10n.offersRadiusLabel;
      case MessageConstants.offersRadiusHint:
        return l10n.offersRadiusHint;
      case MessageConstants.offersLocationRequired:
        return l10n.offersLocationRequired;
      case MessageConstants.offersNoResults:
        return l10n.offersNoResults;
      case MessageConstants.offersNoSearchResults:
        return l10n.offersNoSearchResults;
      case MessageConstants.offersLoadFailure:
        return l10n.offersLoadFailure;
      case MessageConstants.offersRetry:
        return l10n.offersRetry;
      case MessageConstants.offersAdd:
        return l10n.offersAdd;
      case MessageConstants.offersRemove:
        return l10n.offersRemove;
      case MessageConstants.offersHome:
        return l10n.offersHome;
      case MessageConstants.offersList:
        return l10n.offersList;
      case MessageConstants.offersDeviceLocationDenied:
        return l10n.offersDeviceLocationDenied;
      case MessageConstants.offersDeviceLocationUnavailable:
        return l10n.offersDeviceLocationUnavailable;
      case MessageConstants.offersAddressNotFound:
        return l10n.offersAddressNotFound;
      default:
        return l10n.unknownError;
    }
  }
}
